// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CaseManagementReports.Models
{
    public partial class Policymaker
    {
        public Policymaker()
        {
            Hospitalpolicy = new HashSet<Hospitalpolicy>();
        }

        public int PolicyMakerId { get; set; }
        public string Username { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }

        public virtual ICollection<Hospitalpolicy> Hospitalpolicy { get; set; }
    }
}